---
engines:
  eslintConfig:
    extends:
      - react-app
    rules:
      no-var: 1
      no-eval: error
      indent:
        - error
        - 2
      quotes:
        - error
        - single
      no-console: warn
      no-plusplus: "off"
      space-before-function-paren:
        - error
        - never
      padded-blocks:
        - error
        - never
      prefer-arrow-callback:
        - 0
        - allowNamedFunctions: true
      prefer-destructuring: warn
      func-names:
        - error
        - never
      no-use-before-define:
        - "off"
        - functions: false
          classes: true
      max-nested-callbacks:
        - error
        - 5
      import/no-unresolved: "off"
      import/extensions: "off"
      react/jsx-filename-extension:
        - 1
        - extensions:
            - .jsx
            - .tsx
      no-unused-vars:
        - error
        - argsIgnorePattern: "^_"
          varsIgnorePattern: "^_"
          caughtErrorsIgnorePattern: "^_"
      "@typescript-eslint/no-unused-vars":
        - error
        - argsIgnorePattern: "^_"
          varsIgnorePattern: "^_"
          caughtErrorsIgnorePattern: "^_"
  stylelint:
    extends: stylelint-config-sass-guidelines
    plugins:
      - stylelint-scss
    rules:
      at-rule-no-unknown: null,
      declaration-property-value-blacklist: null,
      max-nesting-depth: 5,
      selector-max-compound-selectors: 5,
      selector-max-id: 1,
      selector-no-qualifying-type: null,
      scss/at-rule-no-unknown: true,
      scss/selector-no-redundant-nesting-selector: null
