language: node_js
node_js:
  - lts/*
  - node
script: yarn ci
jobs:
  include:
    - stage: coverage
      node_js: node
      script: yarn coverage
    - stage: build
      node_js: node
      script: yarn build
